version: 0.1.{build}
os: Visual Studio 2015

pull_requests:
  do_not_increment_build_number: true

init:
    - ps: git config --global core.autocrlf true

build_script:
    - nuget restore
    - ps: |
        .\scripts\appveyor-build-version.ps1 -version $env:APPVEYOR_BUILD_VERSION
    - msbuild /p:configuration=Release
    - ps:
        .\scripts\appveyor-copy-artifacts.ps1 -version $env:APPVEYOR_BUILD_VERSION

deploy:
    provider: NuGet
    api_key:
        secure: r2N0Yz/cLRBdviAwov0Kk7dUCuwxaHzVpuPi3n4ShXn0ID+/jHkmCERYFoMUiiVy
    artifact: /.*\.nupkg/

artifacts:
    - path: dist\Jubjubnest.Style.DotNet.vsix
    - path: dist\*.nupkg
