version: 0.1.{build}
os: Visual Studio 2015

pull_requests:
  do_not_increment_build_number: true

build_script:
    - nuget restore
    - ps: |
        .\scripts\appveyor-build-version.ps1 -version $env:APPVEYOR_BUILD_VERSION
    - msbuild /p:configuration=Release
    - ps:
        .\scripts\appveyor-copy-artifacts.ps1 -version $env:APPVEYOR_BUILD_VERSION

artifacts:
    - path: dist\Jubjubnest.Style.DotNet.vsix
